module.exports = {
  env: {
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    MICROSOFT_SPEECH_KEY: process.env.MICROSOFT_SPEECH_KEY,
    MICROSOFT_SPEECH_REGION: process.env.MICROSOFT_SPEECH_REGION,
    MICROSOFT_LANGUAGE_KEY: process.env.MICROSOFT_LANGUAGE_KEY,
    MICRISOFT_LANGUAGE_ENDPOINT: process.env.MICRISOFT_LANGUAGE_ENDPOINT,

    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,

    GOOGLE_PROJECT_ID: process.env.GOOGLE_PROJECT_ID,
    GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID,
    GOOGLE_OAUTH_CLIENT_SECRET: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
    GOOGLE_APPLICATION_CREDENTIALS: process.env.GOOGLE_APPLICATION_CREDENTIALS,
  },
};
